/* eslint-disable */
// Generated by Wrangler by running `wrangler --config=wrangler.json types --include-runtime false` (hash: 19b3cd46760dc0067d0b29bf47c4cffc)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./worker/index')
    durableNamespaces: 'Sandbox'
  }
  interface Env {
    NODE_ENV: string
    ENVIRONMENT: string
    LOGGING: string
    WS_PORT: string
    CLOUDFLARE_ACCOUNT_ID: string
    CLOUDFLARE_API_TOKEN: string
    Sandbox: DurableObjectNamespace<import('./worker/index').Sandbox>
    RATE_LIMITER: RateLimit
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string
}
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'NODE_ENV'
        | 'ENVIRONMENT'
        | 'LOGGING'
        | 'WS_PORT'
        | 'CLOUDFLARE_ACCOUNT_ID'
        | 'CLOUDFLARE_API_TOKEN'
      >
    > {}
}
